package:
  name: spatial
  version: 0.1.0

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - cmake>=3.1
    - conda-forge::xtl
    - conda-forge::xtensor
    - python>=3.6
    - numpy>=1.16
    - conda-forge::pybind11
    - conda-forge::xtensor-python
    
  run:
    - numpy>=1.16
    - python>=3.6
    
test:
  requires:
    - pytest
  imports:
    - spatial
  
  commands:
    - test -d ${PREFIX}/include/spatial           # [unix]
    - test -f ${PREFIX}/include/spatial/spatial.hpp # [unix]
    - if exist %LIBRARY_PREFIX%\include\spatial\spatial.hpp (exit 0) else (exit 1)  # [win]
    # - make cpp-test
    # -  make python-test

about:
  home:  https://github.com/DerThorsten/spatial
  license: MIT
  license_family: MIT
  
  summary: 'spatial is a library for spatial genomics data'
  description: 'spatial is a library for spatial genomics data'
  documentation_url: https://readthedocs.org/projects/spatial/
  dev_url: https://github.com/DerThorsten/spatial

extra:
  recipe-maintainers:
    - Thorsten Beier

